const express = require('express');
const axios = require('axios');
require('dotenv').config();

const app = express();
const PORT = 3000;

// ===== CONFIGURATION =====
const OLLAMA_API_URL = 'http://localhost:11434/api/generate';
const OLLAMA_MODEL = 'llama3';
const AIRTABLE_TOKEN = 'patOSp4rdH3LjbKT7.64d1597860059e1f27d1343f2619011dd9fa7a38bce300b402558ef3b8c9c61c';
const AIRTABLE_BASE_ID = 'appto4Vzgoo9sxJmt';
const AIRTABLE_TABLE_NAME = 'Table 1';

// Airtable API endpoint
const AIRTABLE_API_URL = `https://api.airtable.com/v0/${AIRTABLE_BASE_ID}/${encodeURIComponent(AIRTABLE_TABLE_NAME)}`;

// ===== MIDDLEWARE =====
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ===== HELPER FUNCTIONS =====

/**
 * Fetch all workflows from Airtable
 */
async function fetchAirtableWorkflows() {
  try {
    console.log('📊 Fetching workflows from Airtable...');
    const response = await axios.get(AIRTABLE_API_URL, {
      headers: {
        Authorization: `Bearer ${AIRTABLE_TOKEN}`,
      },
    });

    const workflows = response.data.records.map((record) => ({
      id: record.id,
      fields: record.fields,
    }));

    console.log(`✅ Fetched ${workflows.length} workflows from Airtable`);
    return workflows;
  } catch (error) {
    console.error('❌ Error fetching from Airtable:', error.message);
    throw new Error('Failed to fetch workflows from Airtable');
  }
}

/**
 * Calculate simple similarity score between user query and workflow description
 * (This is a basic implementation; you can upgrade to vector embeddings later)
 */
function calculateSimilarity(userQuery, workflowDescription) {
  const query = userQuery.toLowerCase().split(' ');
  const description = workflowDescription.toLowerCase();

  let matches = 0;
  query.forEach((word) => {
    if (description.includes(word) && word.length > 2) {
      matches += 1;
    }
  });

  return matches / query.length;
}

/**
 * Find top 3 most similar workflows
 */
function getTop3Workflows(userQuery, workflows) {
  const scored = workflows.map((workflow) => {
    const description = workflow.fields['Description'] || '';
    const score = calculateSimilarity(userQuery, description);
    return { ...workflow, score };
  });

  // Sort by score descending and get top 3
  const top3 = scored.sort((a, b) => b.score - a.score).slice(0, 3);

  console.log('🎯 Top 3 workflows selected:');
  top3.forEach((w, i) => {
    console.log(`  ${i + 1}. ${w.fields['Description']} (score: ${w.score.toFixed(2)})`);
  });

  return top3;
}

/**
 * Call Ollama (local LLM) to generate new workflow JSON
 */
async function generateWorkflowWithOllama(userQuery, top3Workflows) {
  try {
    console.log('🤖 Calling Ollama (local LLM) to generate workflow...');

    // Simpler, shorter prompt for faster generation
    const prompt = `Generate an n8n workflow JSON for: "${userQuery}". 
Return ONLY valid JSON with nodes, connections, and configuration. No explanations.`;

    console.log('📤 Sending request to Ollama...');
    console.log('Model: llama3');
    console.log('Prompt length:', prompt.length);

    const response = await axios.post(
      OLLAMA_API_URL,
      {
        model: OLLAMA_MODEL,
        prompt: prompt,
        stream: false,
        temperature: 0.3,  // Lower temperature = faster, more consistent
      }
    );

    let generatedJSON = response.data.response || '';
    console.log('✅ Workflow generated by Ollama');
    console.log('Response length:', generatedJSON.length);

    return generatedJSON;
  } catch (error) {
    console.error('❌ Error calling Ollama:');
    console.error('Status:', error.response?.status);
    console.error('Message:', error.message);
    console.error('❌ Make sure Ollama is running on http://localhost:11434');
    throw new Error('Failed to generate workflow: ' + error.message);
  }
}

/**
 * Validate JSON string
 */
function validateJSON(jsonString) {
  try {
    JSON.parse(jsonString);
    console.log('✅ JSON is valid');
    return true;
  } catch (error) {
    console.error('❌ JSON validation error:', error.message);
    return false;
  }
}

/**
 * Extract JSON from text (in case Groq returns text + JSON)
 */
function extractJSON(text) {
  // Try to extract JSON block if wrapped in ```json ... ```
  const jsonBlockRegex = /```json\s*([\s\S]*?)\s*```/;
  const match = text.match(jsonBlockRegex);

  if (match && match[1]) {
    return match[1].trim();
  }

  // Try to extract the first valid JSON object/array
  const jsonRegex = /\{[\s\S]*\}|\[[\s\S]*\]/;
  const jsonMatch = text.match(jsonRegex);

  if (jsonMatch) {
    return jsonMatch[0];
  }

  // If nothing found, return original text
  return text;
}

// ===== MAIN ROUTE =====

/**
 * POST /webhook
 * Accepts FormData from chrome extension and returns generated workflow
 */
app.post('/webhook', async (req, res) => {
  try {
    console.log('\n🔔 Webhook triggered!');
    console.log('📝 Request body:', req.body);

    const { command, platform, sessionId } = req.body;

    if (!command) {
      console.warn('⚠️ No command provided');
      return res.status(400).json({
        status: 'error',
        message: 'No command provided',
      });
    }

    console.log(`📋 Processing command: "${command}"`);
    console.log(`🌐 Platform: ${platform}`);
    console.log(`🔑 Session ID: ${sessionId}`);

    // Step 1: Fetch all workflows from Airtable
    const allWorkflows = await fetchAirtableWorkflows();

    // Step 2: Find top 3 most similar workflows
    const top3Workflows = getTop3Workflows(command, allWorkflows);

    // Step 3: Call Ollama to generate new workflow
    const generatedJSON = await generateWorkflowWithOllama(command, top3Workflows);

    // Step 4: Extract JSON if needed
    const cleanJSON = extractJSON(generatedJSON);

    // Step 5: Validate JSON
    const isValid = validateJSON(cleanJSON);

    if (!isValid) {
      console.warn('⚠️ Generated JSON is invalid, returning as-is');
    }

    // Step 6: Prepare response for chrome extension
    const responsePayload = {
      status: 'success',
      display_text: `✅ Workflow generated based on: ${top3Workflows
        .map((w) => w.fields['Description'])
        .join(', ')}`,
      json_data: cleanJSON,
      confidence: top3Workflows[0].score,
      topWorkflows: top3Workflows.map((w) => ({
        description: w.fields['Description'],
        id: w.fields['ID'],
      })),
    };

    console.log('✨ Response ready to send');
    res.json(responsePayload);
  } catch (error) {
    console.error('💥 Error processing webhook:', error.message);
    res.status(500).json({
      status: 'error',
      message: error.message,
    });
  }
});

/**
 * Health check endpoint
 */
app.get('/health', (req, res) => {
  res.json({ status: 'Server is running' });
});

// ===== START SERVER =====
app.listen(PORT, () => {
  console.log(`\n🚀 N8N Copilot Backend Server running on http://localhost:${PORT}`);
  console.log('📡 Webhook endpoint: http://localhost:3000/webhook');
  console.log('💚 Health check: http://localhost:3000/health');
  console.log('\n✅ Ready to receive requests from chrome extension!\n');
});
